FROM node:8.0.0-alpine
RUN apk add --update nginx 
RUN rm -rf /var/cache/apk/*
WORKDIR /usr/src/companies
ADD . /usr/src/companies/
RUN npm i
RUN npm run build 
VOLUME /usr/src/companies
CMD npm start
