FROM node:8.0.0-alpine
RUN apk add --update nginx 
RUN rm -rf /var/cache/apk/*
RUN mkdir -p /run/nginx
WORKDIR /usr/src/companies
ADD . /usr/src/companies/
ADD ./default.conf /etc/nginx/conf.d/default.conf
RUN npm i
RUN npm run build 
VOLUME /usr/src/companies
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
