version: '3'
services:

  company-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/companies
    command: npm run build

  nginx:
     image: registry.jincor.com/frontend/nginx:latest
     volumes:
       - ./dist:/var/apps/cmp
     ports:
        - 80:80
        - 443:443
